"""Add site_url_inventories table

Revision ID: 007
Revises: 006
Create Date: 2026-01-05 23:33:56.995469

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '007'
down_revision: Union[str, None] = '006'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('site_url_inventories',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('project_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('url', sa.String(length=2048), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'url', name='uq_site_url_inventory_project_url')
    )
    op.create_index(op.f('ix_site_url_inventories_project_id'), 'site_url_inventories', ['project_id'], unique=False)
    op.drop_index('ix_generated_file_versions_project_version', table_name='generated_file_versions')
    op.drop_constraint('site_overviews_project_id_key', 'site_overviews', type_='unique')
    op.drop_index('ix_site_overviews_project_id', table_name='site_overviews')
    op.create_index(op.f('ix_site_overviews_project_id'), 'site_overviews', ['project_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_site_overviews_project_id'), table_name='site_overviews')
    op.create_index('ix_site_overviews_project_id', 'site_overviews', ['project_id'], unique=False)
    op.create_unique_constraint('site_overviews_project_id_key', 'site_overviews', ['project_id'])
    op.create_index('ix_generated_file_versions_project_version', 'generated_file_versions', ['project_id', 'version'], unique=True)
    op.drop_index(op.f('ix_site_url_inventories_project_id'), table_name='site_url_inventories')
    op.drop_table('site_url_inventories')
    # ### end Alembic commands ###

